# Generated by Django 2.0.7 on 2018-07-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("repos", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LANG", "Language"),
                            ("OS", "Operating System"),
                            ("JS_LIB", "Javascript Library"),
                            ("PY_LIB", "Python Library"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DependencyUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "minor_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "patch_version",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.Dependency",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repos.Repository",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="dependency", unique_together={("name", "type")}
        ),
        migrations.AlterUniqueTogether(
            name="dependencyusage", unique_together={("dependency", "repo")}
        ),
    ]
