# Generated by Django 2.0.7 on 2018-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Operating System", "Operating System"),
                    ("Javascript Library", "Javascript Library"),
                    ("Python Library", "Python Library"),
                ],
                max_length=100,
            ),
        )
    ]
