# Generated by Django 2.0.7 on 2018-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0003_auto_20180811_1632")]

    operations = [
        migrations.AddField(
            model_name="dependencyusage",
            name="for_production",
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name="dependencyusage",
            name="major_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dependencyusage",
            name="minor_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dependencyusage",
            name="patch_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
