# Generated by Django 2.0.7 on 2018-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0004_auto_20180816_1200")]

    operations = [
        migrations.AlterField(
            model_name="dependencyusage",
            name="for_production",
            field=models.NullBooleanField(verbose_name="production"),
        )
    ]
