# Generated by Django 2.1.1 on 2018-09-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("analytics", "0005_auto_20180817_1654")]

    operations = [
        migrations.AlterModelOptions(
            name="dependency", options={"verbose_name_plural": "dependencies"}
        )
    ]
