# Generated by Django 2.1.1 on 2018-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0006_auto_20180914_1512")]

    operations = [
        migrations.AddField(
            model_name="dependencyusage",
            name="version",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
