# Generated by Django 2.1 on 2018-09-17 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0008_auto_20180907_1348")]

    operations = [
        migrations.CreateModel(
            name="DependencySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("dep_usages_num", models.SmallIntegerField(blank=True, null=True)),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="analytics.Dependency",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="dependencysnapshot", unique_together={("dependency", "timestamp")}
        ),
    ]
