# Generated by Django 2.1.1 on 2018-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0009_auto_20180917_1700")]

    operations = [
        migrations.AlterModelOptions(
            name="dependency", options={"verbose_name_plural": "dependencies"}
        ),
        migrations.AddField(
            model_name="dependency",
            name="health_status",
            field=models.NullBooleanField(default=None, verbose_name="health"),
        ),
    ]
