# Generated by Django 2.1.1 on 2018-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0011_auto_20181030_1438")]

    operations = [
        migrations.AlterField(
            model_name="dependencyusage",
            name="major_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dependencyusage",
            name="minor_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dependencyusage",
            name="patch_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
