# Generated by Django 2.1.7 on 2019-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("analytics", "0014_auto_20181126_1828")]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Operating System", "Operating System"),
                    ("Javascript Library", "Javascript Library"),
                    ("Python Library", "Python Library"),
                    ("Docker Image", "Docker Image"),
                ],
                max_length=100,
            ),
        )
    ]
