# Generated by Django 2.2.9 on 2020-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0015_auto_20191107_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Operating System", "Operating System"),
                    ("Javascript Library", "Javascript Library"),
                    ("Python Library", "Python Library"),
                    ("Go Library", "Go Library"),
                    ("Rust Library", "Rust Library"),
                    ("Erlang Library", "Erlang Library"),
                    ("Docker Image", "Docker Image"),
                ],
                max_length=100,
            ),
        ),
    ]
