# Generated by Django 2.2.16 on 2020-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0017_auto_20200828_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="type",
            field=models.CharField(
                choices=[
                    ("Language", "Language"),
                    ("Operating System", "Operating System"),
                    ("Javascript Library", "Javascript Library"),
                    ("Python Library", "Python Library"),
                    ("Go Library", "Go Library"),
                    ("Rust Library", "Rust Library"),
                    ("Erlang Library", "Erlang Library"),
                    ("Docker Image", "Docker Image"),
                    ("Gitlab-ci.yml", "Gitlab-ci.yml"),
                ],
                max_length=100,
            ),
        ),
    ]
