# Generated by Django 2.2.16 on 2020-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hints",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_form_explanation", models.CharField(max_length=1500)),
                ("library_form_explanation", models.CharField(max_length=1500)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Placeholders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_owner", models.CharField(max_length=250)),
                ("service_name", models.CharField(max_length=250)),
                ("service_description", models.CharField(max_length=250)),
                ("service_impact", models.CharField(max_length=250)),
                ("service_status", models.CharField(max_length=250)),
                ("service_tier", models.CharField(max_length=250)),
                ("service_slack_channel", models.CharField(max_length=250)),
                ("service_sentry_project", models.CharField(max_length=250)),
                ("service_sonarqube_project", models.CharField(max_length=250)),
                ("service_repository", models.CharField(max_length=250)),
                ("service_pagerduty_service", models.CharField(max_length=250)),
                ("service_documentation", models.CharField(max_length=250)),
                ("service_tags", models.CharField(max_length=250)),
            ],
            options={"abstract": False,},
        ),
    ]
