# Generated by Django 2.2.16 on 2020-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Helpers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_docs_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_exclusions",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_impact",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_owner",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_pagerduty_service",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_repository",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_sentry_project",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_slack_channel",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_sonarqube_project",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_status",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_tags",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_tier",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={"verbose_name_plural": "helpers",},
        ),
        migrations.CreateModel(
            name="Hints",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_form_explanation", models.TextField(max_length=1500)),
                ("service_form_explanation", models.TextField(max_length=1500)),
            ],
            options={"verbose_name_plural": "hints",},
        ),
        migrations.CreateModel(
            name="Placeholders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_docs_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_exclusions",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_impact",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_owner",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_pagerduty_service",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_repository",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_sentry_project",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_slack_channel",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_sonarqube_project",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_status",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_tags",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "service_tier",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={"verbose_name_plural": "placeholders",},
        ),
    ]
