# Generated by Django 2.2.16 on 2020-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hints", options={"verbose_name_plural": "hints"},
        ),
        migrations.AlterModelOptions(
            name="placeholders", options={"verbose_name_plural": "placeholders"},
        ),
        migrations.AlterField(
            model_name="hints",
            name="library_form_explanation",
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="hints",
            name="service_form_explanation",
            field=models.TextField(max_length=1500),
        ),
    ]
