# Generated by Django 2.2.16 on 2020-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instance", "0002_auto_20200914_1422"),
    ]

    operations = [
        migrations.CreateModel(
            name="Helpers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_owner", models.CharField(max_length=250)),
                ("service_name", models.CharField(max_length=250)),
                ("service_description", models.CharField(max_length=250)),
                ("service_impact", models.CharField(max_length=250)),
                ("service_status", models.CharField(max_length=250)),
                ("service_tier", models.CharField(max_length=250)),
                ("service_slack_channel", models.CharField(max_length=250)),
                ("service_sentry_project", models.CharField(max_length=250)),
                ("service_sonarqube_project", models.CharField(max_length=250)),
                ("service_repository", models.CharField(max_length=250)),
                ("service_pagerduty_service", models.CharField(max_length=250)),
                ("service_docs_url", models.CharField(max_length=250)),
                ("service_tags", models.CharField(max_length=250)),
            ],
            options={"verbose_name_plural": "helpers",},
        ),
        migrations.RenameField(
            model_name="placeholders",
            old_name="service_documentation",
            new_name="service_docs_url",
        ),
    ]
