# Generated by Django 2.2.7 on 2019-12-05 10:08

from django.db import migrations
from elasticsearch import Elasticsearch
from django.conf import settings


def create_new_indexes(apps, schema_editor):
    es = Elasticsearch(hosts=[settings.ELASTICSEARCH_HOST])

    es.indices.create(index='services', ignore=400)
    es.indices.create(index='analytics', ignore=400)
    es.indices.create(index='open-api', ignore=400)


def remove_indexes(apps, schema_editor):
    es = Elasticsearch(hosts=[settings.ELASTICSEARCH_HOST])
    es.indices.delete(index='services', ignore=[400, 401])
    es.indices.delete(index='analytics', ignore=[400, 401])
    es.indices.delete(index='open-api', ignore=[400, 401])


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(create_new_indexes, reverse_code=remove_indexes),
    ]
