# Generated by Django 2.1.7 on 2019-08-08 10:02

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("repos", "0005_auto_20181024_0950")]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    django.contrib.postgres.fields.citext.CICharField(max_length=100),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.citext.CICharField(max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beta", "beta"),
                            ("production", "production"),
                            ("deprecated", "deprecated"),
                            ("discontinued", "discontinued"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("profit", "profit"),
                            ("customers", "customers"),
                            ("employees", "employees"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "slack_channel",
                    models.CharField(blank=True, max_length=22, null=True),
                ),
                (
                    "sonarqube_project",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("docs_url", models.URLField(blank=True, max_length=500, null=True)),
                ("library_url", models.URLField(blank=True, max_length=500, null=True)),
                ("owner_slug", models.SlugField(max_length=140)),
                ("name_slug", models.SlugField(max_length=140)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repos.Repository",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="library", unique_together={("owner", "name")}
        ),
    ]
