# Generated by Django 2.1.7 on 2019-11-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("libraries", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libraries",
                to="repos.Repository",
            ),
        )
    ]
