# Generated by Django 2.2.9 on 2020-02-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0002_auto_20191101_1019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={"verbose_name_plural": "libraries"},
        ),
    ]
