# Generated by Django 2.2.19 on 2021-06-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0003_rename_plural"),
    ]

    operations = [
        migrations.RenameField(
            model_name="library",
            old_name="status",
            new_name="lifecycle",
        ),
    ]
