# Generated by Django 2.1.3 on 2018-12-05 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0005_auto_20181024_0950"),
        ("auditing", "0001_initial_squashed_0025_auto_20181025_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueCountByKindSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind_key", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("fixed", "fixed"),
                            ("wontfix", "wontfix"),
                            ("not found", "not found"),
                            ("reopened", "reopened"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IssueCountByRepositorySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("fixed", "fixed"),
                            ("wontfix", "wontfix"),
                            ("not found", "not found"),
                            ("reopened", "reopened"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("count", models.PositiveIntegerField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_count_snapshots",
                        to="repos.Repository",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="issuecountbykindsnapshot", unique_together={("kind_key", "timestamp")}
        ),
        migrations.AlterUniqueTogether(
            name="issuecountbyrepositorysnapshot",
            unique_together={("repository", "timestamp")},
        ),
    ]
