# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="kind",
            field=models.CharField(
                choices=[
                    ("repo_config:require_approvals", "repo_config:require_approvals"),
                    ("repo_config:use_rebase", "repo_config:use_rebase"),
                    (
                        "repo_config:reset_approvals_on_push",
                        "repo_config:reset_approvals_on_push",
                    ),
                    (
                        "repo_config:block_on_discussions",
                        "repo_config:block_on_discussions",
                    ),
                    (
                        "repo_config:block_on_ci_failure",
                        "repo_config:block_on_ci_failure",
                    ),
                    ("repo_config:autocancel_ci", "repo_config:autocancel_ci"),
                    ("repo_config:protect_master", "repo_config:protect_master"),
                    ("requirements:use_pip_compile", "requirements:use_pip_compile"),
                ],
                max_length=500,
            ),
        )
    ]
