# Generated by Django 2.1.4 on 2019-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0002_add_issue_count_snapshots")]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="merge_request_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
