# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0002_auto_20171206_1120")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="kind",
            field=models.CharField(
                choices=[
                    ("repo_config:require_approvals", "repo_config:require_approvals"),
                    ("repo_config:use_rebase", "repo_config:use_rebase"),
                    (
                        "repo_config:reset_approvals_on_push",
                        "repo_config:reset_approvals_on_push",
                    ),
                    (
                        "repo_config:block_on_discussions",
                        "repo_config:block_on_discussions",
                    ),
                    (
                        "repo_config:block_on_ci_failure",
                        "repo_config:block_on_ci_failure",
                    ),
                    ("repo_config:autocancel_ci", "repo_config:autocancel_ci"),
                    ("repo_config:protect_master", "repo_config:protect_master"),
                    ("requirements:use_pip_compile", "requirements:use_pip_compile"),
                    ("requirements:use_netrc", "requirements:use_netrc"),
                    (
                        "requirements:set_extra_index_url",
                        "requirements:set_extra_index_url",
                    ),
                    ("requirements:replace_pycrypto", "requirements:replace_pycrypto"),
                    ("requirements:replace_ujson", "requirements:replace_ujson"),
                    ("requirements:use_global_tox", "requirements:use_global_tox"),
                    (
                        "requirements:use_global_pip_tools",
                        "requirements:use_global_pip_tools",
                    ),
                ],
                max_length=500,
            ),
        )
    ]
