# Generated by Django 2.1.4 on 2019-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0002_add_issue_count_snapshots")]

    operations = [
        migrations.AddField(
            model_name="issue", name="deleted", field=models.BooleanField(default=False)
        )
    ]
