# Generated by Django 2.1.4 on 2019-02-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0003_issue_deleted"),
        ("auditing", "0003_issue_merge_request_id"),
    ]

    operations = []
