# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:32
from __future__ import unicode_literals

from django.db import migrations


def rename_issue_kinds(apps, schema_editor):
    Issue = apps.get_model("auditing", "Issue")
    for issue in Issue.objects.all():
        old_name = issue.kind
        issue.kind_key = old_name.replace("repo_config:", "gitlab_config:").replace(
            "requirements:", "py_requirements:"
        )
        issue.save()


class Migration(migrations.Migration):

    dependencies = [("auditing", "0004a_auto_20171206_1432")]

    operations = [migrations.RunPython(rename_issue_kinds)]
