# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0004c_auto_20171206_1432")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="kind_key",
            field=models.CharField(
                choices=[
                    (
                        "gitlab_config:require_approvals",
                        "gitlab_config:require_approvals",
                    ),
                    ("gitlab_config:use_rebase", "gitlab_config:use_rebase"),
                    (
                        "gitlab_config:reset_approvals_on_push",
                        "gitlab_config:reset_approvals_on_push",
                    ),
                    (
                        "gitlab_config:block_on_discussions",
                        "gitlab_config:block_on_discussions",
                    ),
                    (
                        "gitlab_config:block_on_ci_failure",
                        "gitlab_config:block_on_ci_failure",
                    ),
                    ("gitlab_config:autocancel_ci", "gitlab_config:autocancel_ci"),
                    ("gitlab_config:protect_master", "gitlab_config:protect_master"),
                    (
                        "py_requirements:use_pip_compile",
                        "py_requirements:use_pip_compile",
                    ),
                    ("py_requirements:use_netrc", "py_requirements:use_netrc"),
                    (
                        "py_requirements:set_extra_index_url",
                        "py_requirements:set_extra_index_url",
                    ),
                    (
                        "py_requirements:replace_pycrypto",
                        "py_requirements:replace_pycrypto",
                    ),
                    ("py_requirements:replace_ujson", "py_requirements:replace_ujson"),
                    (
                        "py_requirements:use_global_tox",
                        "py_requirements:use_global_tox",
                    ),
                    (
                        "py_requirements:use_global_pip_tools",
                        "py_requirements:use_global_pip_tools",
                    ),
                    (
                        "py_requirements:remove_py2_only_reqs",
                        "py_requirements:remove_py2_only_reqs",
                    ),
                    (
                        "py_requirements:keep_https_enforced",
                        "py_requirements:keep_https_enforced",
                    ),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("new", "new"), ("fixed", "fixed")],
                default="new",
                max_length=100,
            ),
        ),
    ]
