# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auditing", "0005_auto_20171214_1420")]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="params",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        )
    ]
