# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0006_issue_params")]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="gitlab_issue_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
