# Generated by Django 2.0.3 on 2018-04-11 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auditing", "0014_auto_20180329_1334")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="params",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        )
    ]
