# Generated by Django 2.0.3 on 2018-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0017_auto_20180426_1609")]

    operations = [
        migrations.AlterField(
            model_name="issue", name="kind_key", field=models.CharField(max_length=500)
        )
    ]
