# Generated by Django 2.0.3 on 2018-06-26 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("auditing", "0018_auto_20180528_0959")]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="last_check",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
