# Generated by Django 2.0.3 on 2018-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auditing", "0019_issue_last_check")]

    operations = [
        migrations.RenameField(
            model_name="issue", old_name="params", new_name="details"
        )
    ]
