# Generated by Django 2.1 on 2018-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auditing", "0020_auto_20180807_0927")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("fixed", "fixed"),
                    ("wontfix", "wontfix"),
                    ("not found", "not found"),
                    ("reopened", "reopened"),
                ],
                default="new",
                max_length=100,
            ),
        )
    ]
