# Generated by Django 2.1 on 2018-08-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0002_add_indexes"),
        ("auditing", "0021_add_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.ContentType",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="repository",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="repos.Repository",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE auditing_issue SET repository_id = object_id",
            "UPDATE auditing_issue SET object_id = repository_id, content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'repos' AND model = 'repository')",
        ),
        migrations.RemoveField(model_name="issue", name="content_type"),
        migrations.RemoveField(model_name="issue", name="object_id"),
    ]
