# Generated by Django 2.1.1 on 2018-10-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auditing", "0024_remove_unhealthy_package_issue")]

    operations = [
        migrations.RenameField(
            model_name="issue", old_name="gitlab_issue_id", new_name="remote_issue_id"
        )
    ]
