# Generated by Django 2.2.19 on 2021-06-17 00:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0004_auto_20210617_0010"),
        ("repos", "0007_endpoint"),
        ("services", "0027_auto_20210617_0010"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=32)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("kind", models.CharField(max_length=16)),
                ("owner", models.CharField(max_length=50)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Used for filtering and defining presets of checks",
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_owner", models.CharField(max_length=100)),
                ("project_owner", models.CharField(max_length=100)),
                (
                    "maintainers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="List of maintainers",
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="https://fomantic-ui.com/elements/icon.html",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        related_query_name="link",
                        to="components.Component",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="component",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                related_query_name="component",
                to="components.Group",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="library",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="libraries.Library",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.Service",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                related_query_name="component",
                to="repos.Repository",
            ),
        ),
    ]
