# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="dashboard_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="docs_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="pagerduty_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
