# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0002_auto_20171101_0943")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="health_check_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        )
    ]
