# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_health_check_url"),
        ("repos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Repository"),
        migrations.AlterField(
            model_name="service",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="repos.Repository",
            ),
        ),
    ]
