# Generated by Django 2.0.7 on 2018-07-20 07:43

import re
from django.db import migrations, models


def generate_owner_slug(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    for service in Service.objects.all():
        service.owner_slug = re.sub("[^0-9a-zA-Z]+", "-", service.owner)
        service.full_clean()
        service.save()


class Migration(migrations.Migration):

    dependencies = [("services", "0004_auto_20171108_1032")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="owner_slug",
            field=models.SlugField(default="", max_length=140),
            preserve_default=False,
        ),
        migrations.RunPython(generate_owner_slug),
    ]
