# Generated by Django 2.1 on 2018-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0006_service_name_slug")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        )
    ]
