# Generated by Django 2.1 on 2018-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0007_service_service_url")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sentry_project",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
