# Generated by Django 2.1.1 on 2018-09-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("services", "0008_service_sentry_project")]

    operations = [
        migrations.CreateModel(
            name="SentryIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("culprit", models.CharField(blank=True, max_length=200)),
                ("short_id", models.CharField(max_length=250)),
                ("issue_id", models.IntegerField()),
                ("assignee", models.CharField(blank=True, max_length=50, null=True)),
                ("permalink", models.URLField(max_length=500)),
                ("events", models.IntegerField()),
                ("users", models.IntegerField()),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stale", "stale"),
                            ("decaying", "decaying"),
                            ("spoiled", "spoiled"),
                            ("fresh", "fresh"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SentryIssueStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("count", models.IntegerField()),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="services.SentryIssue",
                    ),
                ),
            ],
            options={"verbose_name_plural": "sentry issue stats"},
        ),
        migrations.AddField(
            model_name="service",
            name="rating_grade",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="rating_reason",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="sentryissue",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentry_issues",
                to="services.Service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sentryissuestats", unique_together={("timestamp", "issue")}
        ),
    ]
