# Generated by Django 2.1.3 on 2018-11-19 06:14

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0009_sentryissue_sentryissuestats")]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="owner",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100),
        ),
    ]
