# Generated by Django 2.1.4 on 2019-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0011_service_tags")]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sonarqube_project",
            field=models.CharField(blank=True, max_length=250, null=True),
        )
    ]
