# Generated by Django 2.1.7 on 2019-05-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0012_service_sonarqube_project")]

    operations = [
        migrations.DeleteModel(name="DataCenter"),
        migrations.RemoveField(model_name="service", name="datacenter"),
    ]
