# Generated by Django 2.1.7 on 2019-10-11 12:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def move_data(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    Environment = apps.get_model("services", "Environment")

    for service in Service.objects.all():
        Environment.objects.create(
            service_id=service.id,
            name="default",
            service_urls=[service.service_url] if service.service_url else [],
            health_check_url=service.health_check_url,
            dashboard_url=service.dashboard_url,
        )


def move_data_reverse(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    Environment = apps.get_model("services", "Environment")

    for environment in Environment.objects.filter(name="default").all():
        service = Service.objects.get(id=environment.service_id)
        service.service_url = (
            environment.service_urls[0] if environment.service_urls else None
        )
        service.dashboard_url = environment.dashboard_url
        service.health_check_url = environment.health_check_url
        service.save()


class Migration(migrations.Migration):

    dependencies = [("services", "0013_auto_20190515_1451")]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "service_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "health_check_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "dashboard_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                related_query_name="environment",
                to="services.Service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="environment", unique_together={("service", "name")}
        ),
        migrations.RunPython(move_data, reverse_code=move_data_reverse),
        migrations.RemoveField(model_name="service", name="dashboard_url"),
        migrations.RemoveField(model_name="service", name="health_check_url"),
        migrations.RemoveField(model_name="service", name="service_url"),
        migrations.AlterField(
            model_name="service",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="repos.Repository",
            ),
        ),
    ]
