# Generated by Django 2.2.9 on 2020-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_increase_slack_name_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="logs_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
