# Generated by Django 2.2.12 on 2020-08-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_environment_logs_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=80)),
                ("description", models.TextField()),
            ],
            options={"ordering": ["level"],},
        ),
        migrations.AddField(
            model_name="service",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="services.Tier",
            ),
        ),
    ]
