# Generated by Django 2.2.16 on 2020-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_add_service_tier_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="open_api_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
