# Generated by Django 2.2.12 on 2020-08-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_owner_and_name_as_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short description of this service",
                max_length=200,
            ),
        ),
    ]
