# Generated by Django 2.2.12 on 2020-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_add_environment_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="owner",
            field=models.CharField(max_length=100),
        ),
    ]
