# Generated by Django 2.2.12 on 2020-09-01 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_remove_service_pagerduty_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Used for filtering and define presets of checks",
                size=None,
            ),
        ),
    ]
