# Generated by Django 2.2.12 on 2020-08-27 17:09

import re

from django.db import migrations, models
from django.db.models.functions import Concat

DEFAULT_URL = "https://example.pagerduty.com/"


def to_pagerduty_service(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    db_alias = schema_editor.connection.alias
    regex = re.compile(r"https?.*\.[a-z]+/(.*)")
    for service in (
        Service.objects.using(db_alias)
        .exclude(pagerduty_url="")
        .exclude(pagerduty_url__isnull=True)
    ):
        match = regex.match(service.pagerduty_url)
        if match:
            service.pagerduty_service = match.group(1)
            service.save()


def to_pagerduty_url(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    db_alias = schema_editor.connection.alias
    Service.objects.using(db_alias).exclude(pagerduty_service="").update(
        pagerduty_url=Concat(models.Value(DEFAULT_URL), models.F("pagerduty_service"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_add_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="pagerduty_service",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.RunPython(to_pagerduty_service, to_pagerduty_url),
    ]
