# Generated by Django 2.2.16 on 2020-09-14 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_update_help_text_on_tags_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Used for filtering and defining presets of checks",
                size=None,
            ),
        ),
    ]
