# Generated by Django 2.2.16 on 2020-09-08 17:12

from django.db import migrations


def remove_default_general_tag(apps, schema_editor):
    Service = apps.get_model("services", "Service")

    for service in Service.objects.all():
        try:
            service.tags.remove("general")
        except ValueError:
            pass

        service.save()


class Migration(migrations.Migration):

    dependencies = [("services", "0024_update_help_text_on_tags_field")]

    operations = [
        migrations.RunPython(remove_default_general_tag),
    ]
