# Generated by Django 2.2.16 on 2020-11-06 15:57

from django.db import migrations, models

import zoo.services.constants


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_remove_general_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="type",
            field=models.CharField(
                choices=[("gitlab", "gitlab"), ("zoo", "zoo")],
                default=zoo.services.constants.EnviromentType("zoo"),
                max_length=100,
                null=True,
            ),
        ),
    ]
