# Generated by Django 2.2.19 on 2021-04-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_remove_general_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="https://fomantic-ui.com/elements/icon.html",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        related_query_name="link",
                        to="services.Service",
                    ),
                ),
            ],
        ),
    ]
