# Generated by Django 2.2.16 on 2021-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_remove_general_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="type",
            field=models.CharField(
                choices=[("gitlab", "gitlab"), ("zoo", "zoo")],
                max_length=100,
                null=True,
            ),
        ),
    ]
