# Generated by Django 2.2.16 on 2020-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0026_environment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="type",
            field=models.CharField(
                choices=[("gitlab", "gitlab"), ("zoo", "zoo")],
                max_length=100,
                null=True,
            ),
        ),
    ]
