# Generated by Django 2.2.19 on 2021-06-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0026_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="status",
            new_name="lifecycle",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
