# Generated by Django 2.2.19 on 2021-07-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_auto_20210509_1900"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="status",
            new_name="lifecycle",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
