# Generated by Django 2.2.19 on 2021-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_auto_20210509_1900"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="status",
            new_name="lifecycle",
        ),
        migrations.AlterField(
            model_name="service",
            name="pagerduty_service",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
