# Generated by Django 2.2.19 on 2021-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="product_owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
