# Generated by Django 2.2.19 on 2021-10-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_allow_null_product_owner_on_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entities.Group",
            ),
        ),
    ]
