# Generated by Django 2.1.7 on 2019-05-21 14:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import zoo.datacenters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("services", "0013_auto_20190515_1451")]

    operations = [
        migrations.CreateModel(
            name="Datacenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InfraNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("kind", models.CharField(max_length=50)),
                (
                    "checked_at",
                    models.DateTimeField(default=zoo.datacenters.models.utcnow),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        related_name="targets",
                        related_query_name="target",
                        to="datacenters.InfraNode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceDatacenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datacenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datacenters.Datacenter",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.Service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceDatacenterComponent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "service_datacenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        related_query_name="component",
                        to="datacenters.ServiceDatacenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceDatacenterMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                (
                    "service_datacenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        related_query_name="member",
                        to="datacenters.ServiceDatacenter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datacenter",
            name="services",
            field=models.ManyToManyField(
                related_name="datacenters",
                related_query_name="datacenter",
                through="datacenters.ServiceDatacenter",
                to="services.Service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicedatacenter", unique_together={("service", "datacenter")}
        ),
        migrations.AlterUniqueTogether(
            name="servicedatacentercomponent",
            unique_together={("service_datacenter", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="servicedatacentermember",
            unique_together={("service_datacenter", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="infranode", unique_together={("value", "kind")}
        ),
        migrations.AlterUniqueTogether(
            name="datacenter", unique_together={("provider", "region")}
        ),
    ]
