# Generated by Django 2.1.7 on 2019-11-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("datacenters", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="datacenter", name="services"),
        migrations.AlterField(
            model_name="servicedatacenter",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datacenters",
                to="services.Service",
            ),
        ),
    ]
