# Generated by Django 2.1 on 2018-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("repos", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
