# Generated by Django 2.1.1 on 2018-10-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("repos", "0003_auto_20180914_1512")]

    operations = [
        migrations.RenameField(
            model_name="repository", old_name="gitlab_id", new_name="remote_id"
        )
    ]
