# Generated by Django 2.1.1 on 2018-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("repos", "0004_auto_20181001_1038")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="provider",
            field=models.CharField(
                choices=[("gitlab", "gitlab"), ("github", "github")],
                default="gitlab",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repository", name="remote_id", field=models.IntegerField()
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("remote_id", "provider", "owner", "name")},
        ),
    ]
