# Generated by Django 2.2.16 on 2020-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0005_auto_20181024_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="exclusions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma separated paths to exclude from checks",
                max_length=500,
            ),
        ),
    ]
