# Generated by Django 2.2.16 on 2020-11-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0006_repository_exclusions"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryEnvironments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("external_url", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("gitlab", "gitlab"), ("github", "github")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_environments",
                        related_query_name="repository_environment",
                        to="repos.Repository",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("repository", "name")},
            },
        ),
    ]
