# Generated by Django 2.2.18 on 2021-03-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0006_repository_exclusions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=10)),
                ("summary", models.CharField(blank=True, max_length=500, null=True)),
                ("operation", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="repos.Repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("path", "method", "repository")},
            },
        ),
    ]
