# Generated by Django 2.2.16 on 2020-11-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0007_repositoryenvironments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RepositoryEnvironments",
            new_name="RepositoryEnvironment",
        ),
    ]
