# Generated by Django 2.2.19 on 2021-03-28 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0007_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryEnvironment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("external_url", models.CharField(max_length=100, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_environments",
                        related_query_name="repository_environment",
                        to="repos.Repository",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("repository", "name")},
            },
        ),
    ]
