# Generated by Django 2.1.3 on 2018-11-27 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("services", "0011_service_tags")]

    operations = [
        migrations.CreateModel(
            name="Checkmark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_key", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkmarks",
                        to="services.Service",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="checkmark", unique_together={("service", "step_key")}
        ),
    ]
