# Generated by Django 2.1.7 on 2019-08-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_service_sonarqube_project"),
        ("libraries", "0001_initial"),
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkmark",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkmarks",
                to="libraries.Library",
            ),
        ),
        migrations.AlterField(
            model_name="checkmark",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkmarks",
                to="services.Service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkmark", unique_together={("service", "library", "step_key")}
        ),
    ]
